### ISSUE TITLE
Bug: AlgaSynthDef does not compile correctly when line of code to be wrapped in Out UGen also declares a variable

### ISSUE THREAD

**Issue by thresholdpeople** [vitreo12/AlgaLib#62]
When declaring a variable on the same line as the returned value (theoretically the signal to be wrapped in an Out UGen), the AlgaSynthDef fails to compile correctly, but fails silently.

```
(
AlgaSynthDef(\sineLFO, {
	var freq = \freq.kr(10);
	var sig = SinOsc.ar(freq);
}).add 
)
// there is no error or warning when evaluating the above code block


a = AlgaNode(\sineLFO) // no error posted, though fails silently

b = AlgaNode({ Pulse.ar(\freq.kr(440), \width.kr(0.5)) * \amp.kr(0.2) ! 2 }).play

b.from(a, \freq, scale: [-1, 1, 300, 400]) // causes freq to change, but not as expected
```

So when it fails like this, trying to use the AlgaSynth to modulate a bus also doesn't work.

While attempting to troubleshoot, I noticed the following thing will happen:
```
// evaluating this line:
a = AlgaNode(\sineLFO, [\freq, 150]).play;
// returns:
// ERROR: AlgaNode: cannot play a kr node
```

I know that for this purpose I wouldn't need to `play` the node, but it's how I realized something was going wrong.

This issue is the same even if setting `sampleAccurate: true`. 

  
  

However, if I structure the AlgaSynthDef differently, everything works as expected:
```
(
AlgaSynthDef(\sineLFO, {
	var freq = \freq.kr(10);
	var sig;
        sig = SinOsc.ar(freq);
}).add 
)
// or
(
AlgaSynthDef(\sineLFO, {
	var freq = \freq.kr(10);
        SinOsc.ar(freq);
}).add 
)

// works:
a = AlgaNode(\sineLFO, [\freq, 150]).play;

a.disconnect;

// and works here too:
a = AlgaNode(\sineLFO)

b = AlgaNode({ Pulse.ar(\freq.kr(440), \width.kr(0.5)) * \amp.kr(0.2) ! 2 }).play
b.from(a, \freq, scale: [-1, 1, 300, 400])
```

**Comment by vitreo12** [comment]
Great catch!

I have pushed a change on the develop branch which actually also gave me the chance of reviewing a bit of the error handling in `AlgaSynthDef`. 

It works on my end, but could you test it out on yours too?

**Comment by thresholdpeople** [comment]
Mine behaves the same way, and even if ignoring the warning and trying to use it anyway, it no longer creates a strange offset- just silently does nothing. 

Thanks so much for looking into it. For some reason not having to provide `In`s, `Out`s, or set up busses for modulation, coupled with this error really confused me for a while. Now I'm getting a firmer grasp on it.

Want me to close this issue, or shall I leave it to you?

**Comment by vitreo12** [comment]
I can close it, no problems.

One more thing. With "just silently does nothing" you mean that it does not allow you to instantiate an `AlgaNode`, right? It should not allow you to define the `AlgaSynthDef`.

**Comment by vitreo12** [comment]
Well it actually will try to instantiate the node, and fail with an error after 5 seconds.

**Comment by thresholdpeople** [comment]
Oh, yes, sorry, there is an error, immediately, and just as you describe: `ERROR: AlgaNode: Invalid AlgaSynthDef: 'sineLFO'`.

**Comment by vitreo12** [comment]
Great, I'll mark this as fixed then :)
