### ISSUE TITLE
Bug [Develop Branch] - AlgaNode replace method not removing replaced node from the server

### ISSUE THREAD

**Issue by thresholdpeople** [vitreo12/AlgaLib#69]
I'm using the Develop branch and I noticed that when calling `replace` on an `AlgaNode`, the previous node remains on the server. It is no longer audible, so `stop` seems to be called, but it's still running. It's easy to spot with this code:

```
a = AN({ SinOsc.ar(100) * 0.2.poll }).play

a.replace({ SinOsc.ar(400) * 0.2 })
```

After evaluating the `replace` line, the 100Hz sine will no longer be heard, but the `poll`ing will continue. The node will still also be visible on the node tree. 

This behavior is consistent whether using a predefined `AlgaSynthDef` or providing a function as above. 

I tried this on the master branch and the behavior is not there... replace fully replaces the nodes.

`AlgaPattern` also seems to be working as expected.

**Comment by vitreo12** [comment]
Good catch! I had a wrong default value for a `\gate` parameter. It is now fixed on develop :)
