### ISSUE TITLE
[Develop Branch] AlgaOut Error

### ISSUE THREAD

**Issue by thresholdpeople** [vitreo12/AlgaLib#70]
I can't seem to get `AlgaOut` working. I'm not sure if it's something I'm doing, but the example code in AlgaOut's help file is presenting the same error message:

```
*** ERROR: SynthDef sine_algaPattern_algaPatternTempOut not found
FAILURE IN SERVER /s_new SynthDef not found
```

If I remove the `out` key the `AP` plays as expected.

**Comment by vitreo12** [comment]
Great catch as always: I forgot that I changed some of the underlying names of the AlgaSynthDefs. It's now fixed :)
