### ISSUE TITLE
(low priority) AlgaPattern: Pdup in def

### ISSUE THREAD

**Issue by thresholdpeople** [vitreo12/AlgaLib#72]
Hello Francesco! 

Would it be possible to allow `Pdup` to be used in `AlgaPattern`'s def? 

```
(
~source = AP(
	(
		def: Pdup(Pwhite(1, 4), Prand([
			{ SinOsc.ar(\freq.kr(440)) * \amp.kr(1) },
			{ LFTri.ar(\freq.kr(440)) * \amp.kr(1) },
			{ LFSaw.ar(\freq.kr(440)) * \amp.kr(1) },
			{ LFPulse.ar(\freq.kr(440)) * \amp.kr(1) },
		], inf)),
		dur: Pseq([0.5, 0.3, 0.3, 0.5], inf),
		freq: Pdup(Pseq((1..4) ++ [3, 2], inf), Pseq([500, 700, 350], inf)),
		amp: AlgaTemp(
			(
				def: { EnvPerc.kr(\att.kr(0.01), \rel.kr(0.6), \curve.kr(-4)) * \amp.kr(1) },
				att: Pwhite(0.01, 0.1),
				rel: Pmeanrand(0.4, 0.8),
				curve: Pwhite(-1, -6),
				amp: Pwhite(0.7, 1.0),
			)
		),
		
	),
	0.25
).play(chans: 2)
)
```

This currently returns the following error: `ERROR: AlgaPattern: 'a Pdup' is an invalid 'def'`.

**Comment by vitreo12** [comment]
This is a very valid point.

Right now only direct `ListPatterns` are supported, but arguably `FilterPatterns` (which `Pdup` inherits from) should be supported. I will look into it in the next couple of days, it should be an easy fix :)

**Comment by vitreo12** [comment]
I have pushed the changes to develop, do you want to test them out with your code?

**Comment by thresholdpeople** [comment]
It seems to be working great! Thank you!

**Comment by vitreo12** [comment]
Great, closing it then :)
